// 本文件由 `node scripts/gen-endpoint-table.mjs` 生成，请勿手改。
//
// 来源：上游 `apigrpc/apigrpc.swagger.json` 的 paths（去掉厂商前缀后的动作名）。
// 上游 commit：e920249a3465bea4b8ea2968020c488201b61a8e
//
// 用途：路由分发的唯一真相来源。已实现的路径走真实处理器；表里存在但尚未实现的
// 路径返回 501 Unimplemented（与上游 HTTPStatusFromCode 对 Unimplemented 的映射一致），
// 表里不存在的路径才返回 404 Not Found。

import type { UpstreamEndpoint } from "./endpoints";

export const UPSTREAM_COMMIT = "e920249a3465bea4b8ea2968020c488201b61a8e";

export const UPSTREAM_REST_ENDPOINTS: readonly UpstreamEndpoint[] = [
  { method: "GET", path: "/healthcheck", operation: "Healthcheck", auth: "none" },
  { method: "DELETE", path: "/v2/account", operation: "DeleteAccount", auth: "user" },
  { method: "GET", path: "/v2/account", operation: "GetAccount", auth: "user" },
  { method: "PUT", path: "/v2/account", operation: "UpdateAccount", auth: "user" },
  { method: "POST", path: "/v2/account/authenticate", operation: "Authenticate", auth: "server-key" },
  { method: "POST", path: "/v2/account/authenticate/apple", operation: "AuthenticateApple", auth: "server-key" },
  { method: "POST", path: "/v2/account/authenticate/custom", operation: "AuthenticateCustom", auth: "server-key" },
  { method: "POST", path: "/v2/account/authenticate/device", operation: "AuthenticateDevice", auth: "server-key" },
  { method: "POST", path: "/v2/account/authenticate/email", operation: "AuthenticateEmail", auth: "server-key" },
  { method: "POST", path: "/v2/account/authenticate/facebook", operation: "AuthenticateFacebook", auth: "server-key" },
  { method: "POST", path: "/v2/account/authenticate/facebookinstantgame", operation: "AuthenticateFacebookInstantGame", auth: "server-key" },
  { method: "POST", path: "/v2/account/authenticate/gamecenter", operation: "AuthenticateGameCenter", auth: "server-key" },
  { method: "POST", path: "/v2/account/authenticate/google", operation: "AuthenticateGoogle", auth: "server-key" },
  { method: "POST", path: "/v2/account/authenticate/steam", operation: "AuthenticateSteam", auth: "server-key" },
  { method: "POST", path: "/v2/account/link", operation: "Link", auth: "user" },
  { method: "POST", path: "/v2/account/link/apple", operation: "LinkApple", auth: "user" },
  { method: "POST", path: "/v2/account/link/custom", operation: "LinkCustom", auth: "user" },
  { method: "POST", path: "/v2/account/link/device", operation: "LinkDevice", auth: "user" },
  { method: "POST", path: "/v2/account/link/email", operation: "LinkEmail", auth: "user" },
  { method: "POST", path: "/v2/account/link/facebook", operation: "LinkFacebook", auth: "user" },
  { method: "POST", path: "/v2/account/link/facebookinstantgame", operation: "LinkFacebookInstantGame", auth: "user" },
  { method: "POST", path: "/v2/account/link/gamecenter", operation: "LinkGameCenter", auth: "user" },
  { method: "POST", path: "/v2/account/link/google", operation: "LinkGoogle", auth: "user" },
  { method: "POST", path: "/v2/account/link/steam", operation: "LinkSteam", auth: "user" },
  { method: "POST", path: "/v2/account/session/refresh", operation: "SessionRefresh", auth: "server-key" },
  { method: "POST", path: "/v2/account/unlink", operation: "Unlink", auth: "user" },
  { method: "POST", path: "/v2/account/unlink/apple", operation: "UnlinkApple", auth: "user" },
  { method: "POST", path: "/v2/account/unlink/custom", operation: "UnlinkCustom", auth: "user" },
  { method: "POST", path: "/v2/account/unlink/device", operation: "UnlinkDevice", auth: "user" },
  { method: "POST", path: "/v2/account/unlink/email", operation: "UnlinkEmail", auth: "user" },
  { method: "POST", path: "/v2/account/unlink/facebook", operation: "UnlinkFacebook", auth: "user" },
  { method: "POST", path: "/v2/account/unlink/facebookinstantgame", operation: "UnlinkFacebookInstantGame", auth: "user" },
  { method: "POST", path: "/v2/account/unlink/gamecenter", operation: "UnlinkGameCenter", auth: "user" },
  { method: "POST", path: "/v2/account/unlink/google", operation: "UnlinkGoogle", auth: "user" },
  { method: "POST", path: "/v2/account/unlink/steam", operation: "UnlinkSteam", auth: "user" },
  { method: "GET", path: "/v2/channel/{channelId}", operation: "ListChannelMessages", auth: "user" },
  { method: "POST", path: "/v2/event", operation: "Event", auth: "user" },
  { method: "DELETE", path: "/v2/friend", operation: "DeleteFriends", auth: "user" },
  { method: "GET", path: "/v2/friend", operation: "ListFriends", auth: "user" },
  { method: "POST", path: "/v2/friend", operation: "AddFriends", auth: "user" },
  { method: "POST", path: "/v2/friend/block", operation: "BlockFriends", auth: "user" },
  { method: "POST", path: "/v2/friend/facebook", operation: "ImportFacebookFriends", auth: "user" },
  { method: "GET", path: "/v2/friend/friends", operation: "ListFriendsOfFriends", auth: "user" },
  { method: "POST", path: "/v2/friend/steam", operation: "ImportSteamFriends", auth: "user" },
  { method: "GET", path: "/v2/group", operation: "ListGroups", auth: "user" },
  { method: "POST", path: "/v2/group", operation: "CreateGroup", auth: "user" },
  { method: "DELETE", path: "/v2/group/{groupId}", operation: "DeleteGroup", auth: "user" },
  { method: "PUT", path: "/v2/group/{groupId}", operation: "UpdateGroup", auth: "user" },
  { method: "POST", path: "/v2/group/{groupId}/add", operation: "AddGroupUsers", auth: "user" },
  { method: "POST", path: "/v2/group/{groupId}/ban", operation: "BanGroupUsers", auth: "user" },
  { method: "POST", path: "/v2/group/{groupId}/demote", operation: "DemoteGroupUsers", auth: "user" },
  { method: "POST", path: "/v2/group/{groupId}/join", operation: "JoinGroup", auth: "user" },
  { method: "POST", path: "/v2/group/{groupId}/kick", operation: "KickGroupUsers", auth: "user" },
  { method: "POST", path: "/v2/group/{groupId}/leave", operation: "LeaveGroup", auth: "user" },
  { method: "POST", path: "/v2/group/{groupId}/promote", operation: "PromoteGroupUsers", auth: "user" },
  { method: "GET", path: "/v2/group/{groupId}/user", operation: "ListGroupUsers", auth: "user" },
  { method: "POST", path: "/v2/iap/purchase/apple", operation: "ValidatePurchaseApple", auth: "user" },
  { method: "POST", path: "/v2/iap/purchase/facebookinstant", operation: "ValidatePurchaseFacebookInstant", auth: "user" },
  { method: "POST", path: "/v2/iap/purchase/google", operation: "ValidatePurchaseGoogle", auth: "user" },
  { method: "POST", path: "/v2/iap/purchase/huawei", operation: "ValidatePurchaseHuawei", auth: "user" },
  { method: "POST", path: "/v2/iap/purchase/samsung", operation: "ValidatePurchaseSamsung", auth: "user" },
  { method: "POST", path: "/v2/iap/subscription", operation: "ListSubscriptions", auth: "user" },
  { method: "GET", path: "/v2/iap/subscription/{productId}", operation: "GetSubscription", auth: "user" },
  { method: "POST", path: "/v2/iap/subscription/apple", operation: "ValidateSubscriptionApple", auth: "user" },
  { method: "POST", path: "/v2/iap/subscription/google", operation: "ValidateSubscriptionGoogle", auth: "user" },
  { method: "DELETE", path: "/v2/leaderboard/{leaderboardId}", operation: "DeleteLeaderboardRecord", auth: "user" },
  { method: "GET", path: "/v2/leaderboard/{leaderboardId}", operation: "ListLeaderboardRecords", auth: "user" },
  { method: "POST", path: "/v2/leaderboard/{leaderboardId}", operation: "WriteLeaderboardRecord", auth: "user" },
  { method: "GET", path: "/v2/leaderboard/{leaderboardId}/owner/{ownerId}", operation: "ListLeaderboardRecordsAroundOwner", auth: "user" },
  { method: "GET", path: "/v2/match", operation: "ListMatches", auth: "user" },
  { method: "GET", path: "/v2/matchmaker/stats", operation: "GetMatchmakerStats", auth: "user" },
  { method: "DELETE", path: "/v2/notification", operation: "DeleteNotifications", auth: "user" },
  { method: "GET", path: "/v2/notification", operation: "ListNotifications", auth: "user" },
  { method: "GET", path: "/v2/party", operation: "ListParties", auth: "user" },
  { method: "GET", path: "/v2/rpc/{id}", operation: "RpcFunc2", auth: "user-or-http-key" },
  { method: "POST", path: "/v2/rpc/{id}", operation: "RpcFunc", auth: "user-or-http-key" },
  { method: "POST", path: "/v2/session/logout", operation: "SessionLogout", auth: "user" },
  { method: "POST", path: "/v2/storage", operation: "ReadStorageObjects", auth: "user" },
  { method: "PUT", path: "/v2/storage", operation: "WriteStorageObjects", auth: "user" },
  { method: "GET", path: "/v2/storage/{collection}", operation: "ListStorageObjects", auth: "user" },
  { method: "GET", path: "/v2/storage/{collection}/{userId}", operation: "ListStorageObjects2", auth: "user" },
  { method: "PUT", path: "/v2/storage/delete", operation: "DeleteStorageObjects", auth: "user" },
  { method: "GET", path: "/v2/tournament", operation: "ListTournaments", auth: "user" },
  { method: "DELETE", path: "/v2/tournament/{tournamentId}", operation: "DeleteTournamentRecord", auth: "user" },
  { method: "GET", path: "/v2/tournament/{tournamentId}", operation: "ListTournamentRecords", auth: "user" },
  { method: "POST", path: "/v2/tournament/{tournamentId}", operation: "WriteTournamentRecord2", auth: "user" },
  { method: "PUT", path: "/v2/tournament/{tournamentId}", operation: "WriteTournamentRecord", auth: "user" },
  { method: "POST", path: "/v2/tournament/{tournamentId}/join", operation: "JoinTournament", auth: "user" },
  { method: "GET", path: "/v2/tournament/{tournamentId}/owner/{ownerId}", operation: "ListTournamentRecordsAroundOwner", auth: "user" },
  { method: "GET", path: "/v2/user", operation: "GetUsers", auth: "user" },
  { method: "GET", path: "/v2/user/{userId}/group", operation: "ListUserGroups", auth: "user" },
];
// integrity: body_sha256=fb7ed215745c085aea686b509c2e2dae7fa05a51ad37566246e9045c5debbbcc
